name: Context/Variable Practice

on: 
  workflow_dispatch:
    inputs:
      number:
        description: "Enter a number"
        required: true
        default: 1
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.number > 7 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release
