name: Context/Variable Practice

on: 
  workflow_dispatch:
  
env: 
  number: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        if: ${{ env.number > 7 }}
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release
