jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: [3.1.x, 5.0.x, 6.0.x]
    if: ${{ github.event.inputs.number > 7 }}

    env:
      JOB_VAR: "Detta är en job-variabel"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release

      - name: Print environment variables
        run: |
          echo "Globala variabler:"
          echo "GLOBAL_VAR=${GLOBAL_VAR}"
          echo "JOB_VAR=${JOB_VAR}"
          STEP_VAR="Detta är en steg-variabel"
          echo "STEP_VAR=${STEP_VAR}"
          echo "Alla miljövariabler:"
          env
