name: My Workflow

on:
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      SLOGAN: ${{ secrets.SLOGAN }}           # Assuming SLOGAN is a secret
      MY_MAGIC_NUMBER: ${{ secrets.MY_MAGIC_NUMBER }}  # Assuming MY_MAGIC_NUMBER is a secret

    steps:
      - name: Run Slogan
        run: echo "${{ env.SLOGAN }}"

      - name: Guess our MY_MAGIC_NUMBER
        run: echo "${{ env.MY_MAGIC_NUMBER }}"
