name: My Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Environment Variable
      run: echo "LANGUAGE_SET: ${{ env.LANGUAGE_SET }}"
      
    - name: Print Repository Variable
      run: echo "SLOGAN: ${{ secrets.SLOGAN }}"
      
    - name: Use MY_VARIABLE
      run: |
        echo "MY_VARIABLE value: ${{ env.MY_VARIABLE }}"
        # Use the value of MY_VARIABLE in your workflow
