name: test-enviroments
on: workflow_dispatch
jobs:
  print-my-variable:
    runs-on: ubuntu-latest
    environment: Test
    env:
      MIN_VARIABLE: ${{ vars.MIN_VARIABLE }} 
    steps:
      - name: Echo Environment Variable
        run: |
          echo "${{ vars.MIN_VARIABLE }}"
          echo $MIN_VARIABLE

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: dotnet run
