name: test-enviroments
on: workflow_dispatch
jobs:
  print-my-variable:
    runs-on: ubuntu-latest
    # Define GITHUB environment to use
    environment: Test
    # Declare environment variables
    env:
      MIN_VARIABEL: ${{ vars.MIN_VARIABEL }} 
    steps:
      - name: Echo Enviroment Variable
      - run: echo "${{ vars.MIN_VARIABEL }}"
      - run: echo $MIN_VARIABEL

      - name: Setup
      - run: actions/checkout@v4

      - name: Build
      - run: dotnet run
      
