name: test-enviroments
on: workflow_dispatch
jobs:
  print-my-variable:
    runs-on: ubuntu-latest
    environment: Test
    env:
      MIN_VARIABLE: ${{ vars.MY_VARIABLE }} 
    steps:
      - name: Echo Environment Variable
        run: |
          echo "${{ vars.MY_VARIABLE }}"
          echo $MIN_VARIABLE
